### ISSUE TITLE
How can UPDATE???

### ISSUE THREAD

**Issue by nregagrm1** [ranvirp/basicmnrega#10]
At the time of registration if attachment is missing ...then how can attach again ???
Or

How can modify comment /information after registration

**Comment by ranvirp** [comment]
Done..Update link is avaiable next to print.

**Comment by nregagrm1** [comment]
Sir,

officer name changes not updated......

(From PO to CDO )

**Comment by ranvirp** [comment]
Please be specific ...write URLs...and also try attaching screenshots ....
I would be able to attend severe bug fixes only and not features....in case
of bugs please whatsapp on my personal number...

On Tue, Oct 6, 2015 at 5:56 PM, nregagrm1 notifications@github.com wrote:

> Sir,
> 
> officer name changes not updated......
> 
> (From PO to CDO )
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ranvirp/basicmnrega/issues/10#issuecomment-145841359.

## 

Ranvir Prasad, IAS

Uttar Pradesh.

09760757867
