### ISSUE TITLE
Arrange Alphabetical Order

### ISSUE THREAD

**Issue by nregagrm1** [ranvirp/basicmnrega#11]
Sir,

If possible please Arrange District, block and Panchayat name in Alphabetical order for create page.

**Comment by ranvirp** [comment]
done.

**Comment by nregagrm1** [comment]
District and Panchayats are arrenged but block not in alphabetical order .....

**Comment by nregagrm1** [comment]
District and Panchayats are arrenged but blocks not in alphabetical order
.....

On 30 September 2015 at 03:41, ranvirp notifications@github.com wrote:

> Closed #11 https://github.com/ranvirp/basicmnrega/issues/11.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ranvirp/basicmnrega/issues/11#event-422449742.

## 

_Thanks with regards,_

_Mahatma Gandhi National Rural Employment Guarantee Scheme 21, Vidhan
Shabha Marg, Lucknow, Uttar Pradesh0522- 4055999/6713408/18001805999_
