### ISSUE TITLE
Pl Check Complaint  ID# 534

### ISSUE THREAD

**Issue by nregagrm1** [ranvirp/basicmnrega#12]
How can submit ATR more than one time from District/ block, this is submitted two times.

1 Id #1294 Action Taken ReportPosted by Program Officer,KAURI RAM| September 25, 2015, 7:55 pm

2.Id #1295 QuestionPosted by Program Officer,KAURI RAM| September 25, 2015, 8:03 pm

**Comment by ranvirp** [comment]
Not a big issue...After status is of ATR received....one can post questions...this does not change status of complaint..known feature...can be disabled if not required....

**Comment by nregagrm1** [comment]
Yes sir,

This feature is not requried...  Sir other users i.e. block and district are not means by this feature. 
so pls disable this option.

**Comment by nregagrm1** [comment]
Respected Sir,

This feature is not requried... Sir other users i.e. block and district are
not means by this feature.
so pls disable this option.

Rgs

Praveen

On 10 October 2015 at 00:32, ranvirp notifications@github.com wrote:

> Not a big issue...After status is of ATR received....one can post
> questions...this does not change status of complaint..known feature...can
> be disabled if not required....
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ranvirp/basicmnrega/issues/12#issuecomment-146962020.

## 

_Thanks with regards,_

_Mahatma Gandhi National Rural Employment Guarantee Scheme 21, Vidhan
Shabha Marg, Lucknow, Uttar Pradesh0522- 4055999/6713408/18001805999_
