### ISSUE TITLE
Create PO login

### ISSUE THREAD

**Issue by nregagrm1** [ranvirp/basicmnrega#13]
Respected Sir 
Good morning
Sir, Some block name are same . so one block ca't open our ID.

Exp-
District                                                Block                                                 status 
Jaunpur                                             Mahrajganj                                         working
Mahrajganj                                        mahrajganj(Sadar)                           not working- can't login
Raibareily                                           mahrajganj                                      not working- can't login
Hardoi                                               Shahabad                                         working
Rampur                                             Shahabad                                         not working- can't login

Sir, Pls do needful

Rgs
Praveen

**Comment by ranvirp** [comment]
The issue has been resolved. Go to Masterdata->designation . Select Program Officer from designation type and select district name from Place...you would see the user id assigned to the designation in the last column. Some of the previous login may have changed ...so you can go to Designation Type->users and then change username ..just being careful that username cannot be duplicate..
So ..Shahabad block of Hardoi district would have login as po_shahabad_3130029 and corresponding password....you can shorten it by going to master data->users
Maharajganj was never duplicate.. not different spellings fro po_maharajganj and po_mahrajganj ...
In any case...there shall be no duplicates convey to officers having duplicate block names  ..new login/passwords

**Comment by nregagrm1** [comment]
Thank you Sir

## Pls find attached sheet.............

_Thanks with regards,_

_Praveen SrivastavaMahatma Gandhi National Rural Employment Guarantee
Scheme 21, Vidhan Shabha Marg, Lucknow, Uttar Pradesh0522-
4055999/6713408/18001805999_

**Comment by ranvirp** [comment]
I cannot find any attachment....
