### ISSUE TITLE
Need editable date for registration 

### ISSUE THREAD

**Issue by nregagrm1** [ranvirp/basicmnrega#14]
Respected Sir,
Please provide edit option for registration date on complaint registration page because when we register old complains the complaint registration date is showing new..... so we are not able to generate date / duration wise pending complaints. Pls update the same so we can register all pending complaints.
Rgs Praveen

**Comment by ranvirp** [comment]
Done. Hopefully working now..

**Comment by nregagrm1** [comment]
Thank you very much Sir..............
