### ISSUE TITLE
Source wise received ATR alert is requried on state login (hl agent 1 to 6)

### ISSUE THREAD

**Issue by nregagrm1** [ranvirp/basicmnrega#4]

**Comment by nregagrm1** [comment]
Ex. CM..GOI..Phone..Ayukt...etc

**Comment by ranvirp** [comment]
Why do you need alerts? Alerts on which parameters...Do you mean to say reports received in last 7 days ??

**Comment by nregagrm1** [comment]
We need alert on Source wise received ATRs from Districts/ blocks. ............. For this information/data we can examine ATRs as per priority basis i.e. GOI, CM, Shasan ...

So parameters are: GOI, Cm off, Shasan etc...(Source of comp.)

**Comment by nregagrm1** [comment]
We need alert on Source wise received ATRs from Districts/ blocks.
............. For this information/data we can examine ATRs as per priority
basis i.e. GOI, CM, Shasan ...

So parameters are: GOI, Cm off, Shasan etc...(Source of comp.)

On 30 September 2015 at 03:40, ranvirp notifications@github.com wrote:

> Why do you need alerts? Alerts on which parameters...Do you mean to say
> reports received in last 7 days ??
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ranvirp/basicmnrega/issues/4#issuecomment-144205798.

## 

_Thanks with regards,_

_Mahatma Gandhi National Rural Employment Guarantee Scheme 21, Vidhan
Shabha Marg, Lucknow, Uttar Pradesh0522- 4055999/6713408/18001805999_

**Comment by ranvirp** [comment]
Now in every report --like -- Received action taken report you can filter by Source....(on top of report)....You can sort the resultant list by clicking on Id, and also by clicking on Last Action time ( Any header in blue is clickable and sortable)...Hope it is sufficient...

**Comment by nregagrm1** [comment]
Thank you Sir

Regards,
Praveen
