### ISSUE TITLE
Name wise search option not working with hindi font

### ISSUE THREAD

**Issue by nregagrm1** [ranvirp/basicmnrega#9]

**Comment by ranvirp** [comment]
Not clear. It is working...

On Mon, Sep 28, 2015 at 2:35 PM, nregagrm1 notifications@github.com wrote:

> —
> Reply to this email directly or view it on GitHub
> https://github.com/ranvirp/basicmnrega/issues/9.

## 

Ranvir Prasad, IAS

Uttar Pradesh.

09760757867

**Comment by nregagrm1** [comment]
http://nregaup.in/index.php/complaint/complaint/create

Font not work google trans.  or krutidev 010

**Comment by nregagrm1** [comment]
http://nregaup.in/index.php/complaint/complaint/create

Font not worked google trans or kruti dev 010

pls do needful

On 30 September 2015 at 03:37, ranvirp notifications@github.com wrote:

> Not clear. It is working...
> 
> On Mon, Sep 28, 2015 at 2:35 PM, nregagrm1 notifications@github.com
> wrote:
> 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ranvirp/basicmnrega/issues/9.
> 
> ## 
> 
> Ranvir Prasad, IAS
> 
> Uttar Pradesh.
> 
> 09760757867
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ranvirp/basicmnrega/issues/9#issuecomment-144205234.

## 

_Thanks with regards,_

_Mahatma Gandhi National Rural Employment Guarantee Scheme 21, Vidhan
Shabha Marg, Lucknow, Uttar Pradesh0522- 4055999/6713408/18001805999_

**Comment by ranvirp** [comment]
I think it is working now....if not open again...

**Comment by nregagrm1** [comment]
Respected Sir

I am not able to find pls see screen shot.

On 10 October 2015 at 00:32, ranvirp notifications@github.com wrote:

> Closed #9 https://github.com/ranvirp/basicmnrega/issues/9.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ranvirp/basicmnrega/issues/9#event-431737659.

## 

_Thanks with regards,_

_Mahatma Gandhi National Rural Employment Guarantee Scheme 21, Vidhan
Shabha Marg, Lucknow, Uttar Pradesh0522- 4055999/6713408/18001805999_

**Comment by ranvirp** [comment]
Ok Now working...so finally closed. Now onwards if you can post such screenshot ..that should be ok..
